FROM openjdk:8-jre-alpine3.9

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add --no-cache py3-pip python3 && \
    apk add --no-cache --virtual build-dependencies python3-dev libffi-dev openssl-dev gcc libc-dev make && \
    pip3 --no-cache-dir install "docker-compose==1.26.0" -i https://mirrors.aliyun.com/pypi/simple && \
    apk del build-dependencies

WORKDIR /opt

CMD ["tail", "-f", "/dev/null"]